name: build_flutter_version
description: Provide app version and git status in a configurable Widget
version: 1.0.0
# homepage: https://github.com/Solido
# author: Robert Felker <flutter@robbieone.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: '>=0.12.1 <2.0.0'
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^0.3.0
  pubspec_parse: ^0.1.2+2
  git: ^0.5.1+1

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3+1
  build_verify: ^1.0.0
  test: ^1.2.0

